### ISSUE TITLE
Tanking Assets

### ISSUE THREAD

**Issue by Theocat321** [A-Level-Personal-Code-Collab/PirateGame#2]
The dragging of assets slows down while placing items on the grid. Last few money items start to slow down and dragging becomes harder
Using google chrome

**Comment by Lime-Parallelogram** [comment]
Such behaviour is not observable on Kubuntu 21.04 (Firefox 90.0) however Firefox on windows definitely seems to be displaying this 'tanking' behaviour. Chrome and Edge also display it to a lesser degree.

**Comment by Lime-Parallelogram** [comment]
This bug has been fixed by disabling the code I had used to remove the ghost image while dragging. In Firefox 90.0 - Kubuntu 21.04 this ghost image was a problem due to the fact that when you end the dragging of an asset, the ghost image appears to float back to the drag origin (cosmetic annoyance).
